### ISSUE TITLE
website doesn't load

### ISSUE THREAD

**Issue by evolsoulx** [jlweston/ngu-save-analyser#41]
Looks like ngusav.es is dead.

**Comment by tiemonl** [comment]
http://www.ngusav.es.s3-website-us-west-2.amazonaws.com/

this is a temporary fix... from the NGU discord:
![image](https://user-images.githubusercontent.com/29804333/101057985-a8c8e900-355a-11eb-9451-e0a6446afa3f.png)

**Comment by evolsoulx** [comment]
The Share Save stuff is the thing I need :(. 

I tried getting it to run locally, but had no luck getting that specific part to function.

**Comment by tiemonl** [comment]
Do you need the Share Save for the outputted JSON? I just worked on it a bit and got the data in json format. I can publish it if need be.

**Comment by evolsoulx** [comment]
Yup, that's what I need it for, to then import into the optimizer.

**Comment by tiemonl** [comment]
I'll post a link here soon for the json fetcher

**Comment by tiemonl** [comment]
@evolsoulx https://github.com/tiemonl/NGUSaveToJSON

**Comment by jlweston** [comment]
Hi all. I'm afraid I don't have the time to maintain this anymore, nor do I play the game enough to keep up to date with any new features. 

As per the screenshot above, @WowSuchRicky has offered to take over the project. I'll close this issue here. Any future issues should be logged over on Ricky's fork.
